-- Stage 5: durable execution, leases, recovery, safety decisions, and race runs.
-- Additive migration. Apply after 001, 002, and 003. Do not edit after deploy;
-- use a follow-up forward migration for future changes.
--
-- The application currently runs with RLS disabled by deployment choice. Keep
-- the Supabase service key server-side; never expose these tables to the UI.

alter table if exists workflow_jobs add column if not exists job_type text not null default 'pentest';
alter table if exists workflow_jobs add column if not exists queue_name text not null default 'general';
alter table if exists workflow_jobs add column if not exists priority integer not null default 100;
alter table if exists workflow_jobs add column if not exists idempotency_key text not null default '';
alter table if exists workflow_jobs add column if not exists risk text not null default 'read_only';
alter table if exists workflow_jobs add column if not exists approval_ref text not null default '';
alter table if exists workflow_jobs add column if not exists config_snapshot jsonb not null default '{}'::jsonb;
alter table if exists workflow_jobs add column if not exists budget jsonb not null default '{}'::jsonb;
alter table if exists workflow_jobs add column if not exists attempt_count integer not null default 0;
alter table if exists workflow_jobs add column if not exists max_attempts integer not null default 3;
alter table if exists workflow_jobs add column if not exists available_at timestamptz not null default now();
alter table if exists workflow_jobs add column if not exists deadline_at timestamptz;
alter table if exists workflow_jobs add column if not exists cancel_requested_at timestamptz;
alter table if exists workflow_jobs add column if not exists checkpoint_id text not null default '';
alter table if exists workflow_jobs add column if not exists lease_owner text not null default '';
alter table if exists workflow_jobs add column if not exists lease_token text not null default '';
alter table if exists workflow_jobs add column if not exists lease_expires_at timestamptz;
alter table if exists workflow_jobs add column if not exists heartbeat_at timestamptz;
alter table if exists workflow_jobs add column if not exists result_ref text not null default '';
alter table if exists workflow_jobs add column if not exists error_code text not null default '';
alter table if exists workflow_jobs add column if not exists error_message text not null default '';
alter table if exists workflow_jobs add column if not exists parent_job_id uuid;

alter table if exists workflow_events add column if not exists event_id text;
alter table if exists workflow_events add column if not exists attempt_id text;
alter table if exists workflow_events add column if not exists sequence bigint generated by default as identity;

create table if not exists workflow_job_attempts (
  attempt_id text primary key,
  job_id uuid not null references workflow_jobs(job_id) on delete cascade,
  attempt_number integer not null default 1,
  worker_id text not null,
  lease_token text not null,
  lease_expires_at timestamptz,
  heartbeat_at timestamptz,
  status text not null default 'leased',
  checkpoint_id text not null default '',
  tool_run_ids jsonb not null default '[]'::jsonb,
  browser_run_ids jsonb not null default '[]'::jsonb,
  resource_usage jsonb not null default '{}'::jsonb,
  retry_class text not null default 'none',
  error_code text not null default '',
  error_message text not null default '',
  started_at timestamptz not null default now(),
  finished_at timestamptz
);

create table if not exists workflow_checkpoints (
  checkpoint_id text primary key,
  job_id uuid not null references workflow_jobs(job_id) on delete cascade,
  attempt_id text not null default '',
  ordinal integer not null default 0,
  phase text not null default '',
  cursor jsonb not null default '{}'::jsonb,
  state_digest text not null default '',
  side_effects jsonb not null default '[]'::jsonb,
  cleanup_refs jsonb not null default '[]'::jsonb,
  evidence_ids jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists worker_nodes (
  worker_id text primary key,
  capabilities jsonb not null default '[]'::jsonb,
  status text not null default 'online',
  last_heartbeat_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists safety_decisions (
  decision_id text primary key,
  session_id uuid not null references sessions(id) on delete cascade,
  job_id uuid references workflow_jobs(job_id) on delete set null,
  attempt_id text not null default '',
  action text not null,
  target text not null default '',
  decision text not null,
  reason_code text not null,
  policy_version text not null default '1.0',
  identity_id text not null default '',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists resource_budget_usage (
  usage_id uuid primary key default gen_random_uuid(),
  session_id uuid not null references sessions(id) on delete cascade,
  job_id uuid references workflow_jobs(job_id) on delete cascade,
  origin text not null default '',
  request_count integer not null default 0,
  uploaded_bytes bigint not null default 0,
  downloaded_bytes bigint not null default 0,
  credential_attempts integer not null default 0,
  updated_at timestamptz not null default now(),
  unique(job_id, origin)
);

create table if not exists target_circuit_breakers (
  session_id uuid not null references sessions(id) on delete cascade,
  origin text not null,
  state text not null default 'closed',
  failure_count integer not null default 0,
  opened_at timestamptz,
  retry_after timestamptz,
  reason text not null default '',
  updated_at timestamptz not null default now(),
  primary key(session_id, origin)
);

create table if not exists sandbox_runs (
  sandbox_run_id text primary key,
  session_id uuid not null references sessions(id) on delete cascade,
  job_id uuid references workflow_jobs(job_id) on delete set null,
  attempt_id text not null default '',
  command_id text not null,
  argv_redacted jsonb not null default '[]'::jsonb,
  status text not null default 'running',
  exit_code integer,
  timed_out boolean not null default false,
  sha256 text not null default '',
  output_bytes integer not null default 0,
  error_code text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists cleanup_attempts (
  cleanup_attempt_id text primary key,
  cleanup_id text not null,
  session_id uuid not null references sessions(id) on delete cascade,
  job_id uuid references workflow_jobs(job_id) on delete set null,
  handler_id text not null,
  status text not null default 'pending',
  context_redacted jsonb not null default '{}'::jsonb,
  verification jsonb not null default '{}'::jsonb,
  error_message text not null default '',
  created_at timestamptz not null default now(),
  finished_at timestamptz
);

create table if not exists race_experiments (
  experiment_id text primary key,
  session_id uuid not null references sessions(id) on delete cascade,
  job_id uuid references workflow_jobs(job_id) on delete set null,
  target text not null,
  method text not null default 'POST',
  request_template_id text not null default '',
  workflow_id text not null default '',
  identity_id text not null default '',
  invariant_id text not null default '',
  mutation_digest text not null default '',
  approval_digest text not null default '',
  schedule jsonb not null default '[2,4,8]'::jsonb,
  baseline_samples integer not null default 3,
  control_samples integer not null default 3,
  status text not null default 'planned',
  cleanup_refs jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists race_attempts (
  attempt_id text primary key,
  experiment_id text not null references race_experiments(experiment_id) on delete cascade,
  role text not null,
  concurrency integer not null default 1,
  sample_number integer not null default 0,
  response_fingerprint text not null default '',
  entity_effect_key text not null default '',
  status_code integer,
  elapsed_ms numeric,
  observation_ids jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create unique index if not exists idx_workflow_jobs_idempotency
  on workflow_jobs(session_id, idempotency_key) where idempotency_key <> '';
create index if not exists idx_workflow_jobs_claim
  on workflow_jobs(queue_name, status, available_at, priority, created_at);
create index if not exists idx_workflow_attempts_lease
  on workflow_job_attempts(status, lease_expires_at);
create index if not exists idx_workflow_events_job_sequence
  on workflow_events(job_id, sequence);
create unique index if not exists idx_workflow_events_event_id
  on workflow_events(event_id) where event_id is not null;
create index if not exists idx_safety_decisions_job
  on safety_decisions(job_id, created_at desc);
create index if not exists idx_race_experiments_session
  on race_experiments(session_id, created_at desc);

create or replace function nexus_append_only() returns trigger
language plpgsql as $$
begin
  raise exception 'append-only record cannot be changed: %', TG_TABLE_NAME;
end;
$$;

drop trigger if exists workflow_events_append_only on workflow_events;
create trigger workflow_events_append_only
before update or delete on workflow_events
for each row execute function nexus_append_only();

drop trigger if exists workflow_checkpoints_append_only on workflow_checkpoints;
create trigger workflow_checkpoints_append_only
before update or delete on workflow_checkpoints
for each row execute function nexus_append_only();

drop trigger if exists safety_decisions_append_only on safety_decisions;
create trigger safety_decisions_append_only
before update or delete on safety_decisions
for each row execute function nexus_append_only();

create or replace function claim_execution_job(
  p_worker_id text,
  p_queues text[] default array['general'],
  p_lease_seconds integer default 60
) returns table(
  job_id uuid,
  attempt_id text,
  attempt_number integer,
  worker_id text,
  lease_token text,
  lease_expires_at timestamptz,
  heartbeat_at timestamptz,
  status text
) language plpgsql security definer as $$
declare
  selected workflow_jobs%rowtype;
  token text := encode(gen_random_bytes(18), 'hex');
  aid text := 'attempt_' || encode(gen_random_bytes(16), 'hex');
  expiry timestamptz := now() + make_interval(secs => greatest(p_lease_seconds, 10));
begin
  select * into selected
  from workflow_jobs
  where queue_name = any(p_queues)
    and status in ('queued', 'retry_wait')
    and available_at <= now()
    and (deadline_at is null or deadline_at > now())
  order by priority asc, created_at asc
  for update skip locked
  limit 1;

  if not found then return; end if;

  update workflow_jobs
  set status = 'leased', lease_owner = p_worker_id, lease_token = token,
      lease_expires_at = expiry, heartbeat_at = now(),
      attempt_count = coalesce(attempt_count, 0) + 1, updated_at = now()
  where workflow_jobs.job_id = selected.job_id;

  insert into workflow_job_attempts(
    attempt_id, job_id, attempt_number, worker_id, lease_token,
    lease_expires_at, heartbeat_at, status
  ) values (
    aid, selected.job_id, coalesce(selected.attempt_count, 0) + 1,
    p_worker_id, token, expiry, now(), 'leased'
  );

  return query select selected.job_id, aid, coalesce(selected.attempt_count, 0) + 1,
    p_worker_id, token, expiry, now(), 'leased'::text;
end;
$$;

create or replace function heartbeat_execution_attempt(
  p_job_id uuid, p_attempt_id text, p_worker_id text,
  p_lease_token text, p_lease_seconds integer default 60
) returns boolean language plpgsql security definer as $$
declare changed integer;
begin
  update workflow_jobs set
    lease_expires_at = now() + make_interval(secs => greatest(p_lease_seconds, 10)),
    heartbeat_at = now(), updated_at = now()
  where job_id = p_job_id and lease_owner = p_worker_id
    and lease_token = p_lease_token and status in ('leased', 'running', 'cancelling');
  get diagnostics changed = row_count;
  if changed = 1 then
    update workflow_job_attempts set heartbeat_at = now(),
      lease_expires_at = now() + make_interval(secs => greatest(p_lease_seconds, 10))
    where attempt_id = p_attempt_id and job_id = p_job_id and worker_id = p_worker_id and lease_token = p_lease_token;
  end if;
  return changed = 1;
end;
$$;

create or replace function transition_execution_job(
  p_job_id uuid, p_attempt_id text, p_worker_id text,
  p_lease_token text, p_status text, p_payload jsonb default '{}'::jsonb
) returns boolean language plpgsql security definer as $$
declare changed integer;
begin
  update workflow_jobs set
    status = p_status,
    checkpoint_id = coalesce(p_payload->>'checkpoint_id', checkpoint_id),
    result_ref = coalesce(p_payload->>'result_ref', result_ref),
    error_code = coalesce(p_payload->>'error_code', error_code),
    error_message = coalesce(p_payload->>'error_message', error_message),
    updated_at = now(),
    lease_expires_at = case when p_status in ('succeeded','partial','failed','cancelled','dead_lettered') then null else lease_expires_at end
  where job_id = p_job_id and lease_owner = p_worker_id and lease_token = p_lease_token;
  get diagnostics changed = row_count;
  if changed = 1 then
    update workflow_job_attempts set status = p_status,
      error_code = coalesce(p_payload->>'error_code', error_code),
      error_message = coalesce(p_payload->>'error_message', error_message),
      finished_at = case when p_status in ('succeeded','partial','failed','cancelled','dead_lettered') then now() else finished_at end
    where attempt_id = p_attempt_id and job_id = p_job_id and worker_id = p_worker_id and lease_token = p_lease_token;
  end if;
  return changed = 1;
end;
$$;

create or replace function recover_expired_execution_jobs() returns integer
language plpgsql security definer as $$
declare recovered integer;
begin
  with expired as (
    update workflow_job_attempts a set status = 'lost', finished_at = now()
    from workflow_jobs j
    where a.job_id = j.job_id and a.status in ('leased','running','waiting')
      and j.lease_expires_at is not null and j.lease_expires_at < now()
    returning j.job_id, j.risk
  )
  update workflow_jobs j set
    status = case when e.risk = 'read_only' then 'retry_wait' else 'recovery_required' end,
    available_at = case when e.risk = 'read_only' then now() + interval '5 seconds' else j.available_at end,
    lease_owner = '', lease_token = '', lease_expires_at = null,
    error_code = case when e.risk = 'read_only' then 'lease_expired' else 'mutation_lease_expired' end,
    updated_at = now()
  from expired e where j.job_id = e.job_id;
  get diagnostics recovered = row_count;
  return recovered;
end;
$$;

