events {}

http {
    server {
        listen 8080;

        location / {
            proxy_set_header Host host.docker.internal:8444;
            proxy_set_header X-Forwarded-Proto http;
            proxy_ssl_server_name on;
            proxy_ssl_name host.docker.internal;
            proxy_ssl_verify off;
            proxy_pass https://host.docker.internal:8444;
        }
    }
}
